/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SituationsRouteImport } from './routes/situations'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SituationsSlugRouteImport } from './routes/situations/$slug'
import { Route as ProvinceProvinceRouteImport } from './routes/province.$province'
import { Route as HelpCategoryRouteImport } from './routes/help/$category'
import { Route as ProvinceProvinceCityRouteImport } from './routes/province.$province.$city'

const SituationsRoute = SituationsRouteImport.update({
  id: '/situations',
  path: '/situations',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsSlugRoute = SituationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SituationsRoute,
} as any)
const ProvinceProvinceRoute = ProvinceProvinceRouteImport.update({
  id: '/province/$province',
  path: '/province/$province',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCategoryRoute = HelpCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => HelpRoute,
} as any)
const ProvinceProvinceCityRoute = ProvinceProvinceCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ProvinceProvinceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRouteWithChildren
  '/situations': typeof SituationsRouteWithChildren
  '/help/$category': typeof HelpCategoryRoute
  '/province/$province': typeof ProvinceProvinceRouteWithChildren
  '/situations/$slug': typeof SituationsSlugRoute
  '/province/$province/$city': typeof ProvinceProvinceCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRouteWithChildren
  '/situations': typeof SituationsRouteWithChildren
  '/help/$category': typeof HelpCategoryRoute
  '/province/$province': typeof ProvinceProvinceRouteWithChildren
  '/situations/$slug': typeof SituationsSlugRoute
  '/province/$province/$city': typeof ProvinceProvinceCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRouteWithChildren
  '/situations': typeof SituationsRouteWithChildren
  '/help/$category': typeof HelpCategoryRoute
  '/province/$province': typeof ProvinceProvinceRouteWithChildren
  '/situations/$slug': typeof SituationsSlugRoute
  '/province/$province/$city': typeof ProvinceProvinceCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/help'
    | '/situations'
    | '/help/$category'
    | '/province/$province'
    | '/situations/$slug'
    | '/province/$province/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/help'
    | '/situations'
    | '/help/$category'
    | '/province/$province'
    | '/situations/$slug'
    | '/province/$province/$city'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/help'
    | '/situations'
    | '/help/$category'
    | '/province/$province'
    | '/situations/$slug'
    | '/province/$province/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRouteWithChildren
  SituationsRoute: typeof SituationsRouteWithChildren
  ProvinceProvinceRoute: typeof ProvinceProvinceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/situations': {
      id: '/situations'
      path: '/situations'
      fullPath: '/situations'
      preLoaderRoute: typeof SituationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations/$slug': {
      id: '/situations/$slug'
      path: '/$slug'
      fullPath: '/situations/$slug'
      preLoaderRoute: typeof SituationsSlugRouteImport
      parentRoute: typeof SituationsRoute
    }
    '/province/$province': {
      id: '/province/$province'
      path: '/province/$province'
      fullPath: '/province/$province'
      preLoaderRoute: typeof ProvinceProvinceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$category': {
      id: '/help/$category'
      path: '/$category'
      fullPath: '/help/$category'
      preLoaderRoute: typeof HelpCategoryRouteImport
      parentRoute: typeof HelpRoute
    }
    '/province/$province/$city': {
      id: '/province/$province/$city'
      path: '/$city'
      fullPath: '/province/$province/$city'
      preLoaderRoute: typeof ProvinceProvinceCityRouteImport
      parentRoute: typeof ProvinceProvinceRoute
    }
  }
}

interface HelpRouteChildren {
  HelpCategoryRoute: typeof HelpCategoryRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpCategoryRoute: HelpCategoryRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface SituationsRouteChildren {
  SituationsSlugRoute: typeof SituationsSlugRoute
}

const SituationsRouteChildren: SituationsRouteChildren = {
  SituationsSlugRoute: SituationsSlugRoute,
}

const SituationsRouteWithChildren = SituationsRoute._addFileChildren(
  SituationsRouteChildren,
)

interface ProvinceProvinceRouteChildren {
  ProvinceProvinceCityRoute: typeof ProvinceProvinceCityRoute
}

const ProvinceProvinceRouteChildren: ProvinceProvinceRouteChildren = {
  ProvinceProvinceCityRoute: ProvinceProvinceCityRoute,
}

const ProvinceProvinceRouteWithChildren =
  ProvinceProvinceRoute._addFileChildren(ProvinceProvinceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRouteWithChildren,
  SituationsRoute: SituationsRouteWithChildren,
  ProvinceProvinceRoute: ProvinceProvinceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
