/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowWeVetRouteImport } from './routes/how-we-vet'
import { Route as HandbookRouteImport } from './routes/handbook'
import { Route as GetVettedRouteImport } from './routes/get-vetted'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SituationsIndexRouteImport } from './routes/situations/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as SituationsSlugRouteImport } from './routes/situations/$slug'
import { Route as ProvinceProvinceRouteImport } from './routes/province.$province'
import { Route as HelpCategoryIndexRouteImport } from './routes/help/$category/index'
import { Route as ProvinceProvinceCityRouteImport } from './routes/province.$province.$city'
import { Route as HelpCategoryArticleRouteImport } from './routes/help/$category/$article'

const HowWeVetRoute = HowWeVetRouteImport.update({
  id: '/how-we-vet',
  path: '/how-we-vet',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookRoute = HandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const GetVettedRoute = GetVettedRouteImport.update({
  id: '/get-vetted',
  path: '/get-vetted',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsIndexRoute = SituationsIndexRouteImport.update({
  id: '/situations/',
  path: '/situations/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsSlugRoute = SituationsSlugRouteImport.update({
  id: '/situations/$slug',
  path: '/situations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvinceProvinceRoute = ProvinceProvinceRouteImport.update({
  id: '/province/$province',
  path: '/province/$province',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCategoryIndexRoute = HelpCategoryIndexRouteImport.update({
  id: '/help/$category/',
  path: '/help/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvinceProvinceCityRoute = ProvinceProvinceCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ProvinceProvinceRoute,
} as any)
const HelpCategoryArticleRoute = HelpCategoryArticleRouteImport.update({
  id: '/help/$category/$article',
  path: '/help/$category/$article',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/founder': typeof FounderRoute
  '/get-vetted': typeof GetVettedRoute
  '/handbook': typeof HandbookRoute
  '/how-we-vet': typeof HowWeVetRoute
  '/province/$province': typeof ProvinceProvinceRouteWithChildren
  '/situations/$slug': typeof SituationsSlugRoute
  '/help/': typeof HelpIndexRoute
  '/situations/': typeof SituationsIndexRoute
  '/help/$category/$article': typeof HelpCategoryArticleRoute
  '/province/$province/$city': typeof ProvinceProvinceCityRoute
  '/help/$category/': typeof HelpCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/founder': typeof FounderRoute
  '/get-vetted': typeof GetVettedRoute
  '/handbook': typeof HandbookRoute
  '/how-we-vet': typeof HowWeVetRoute
  '/province/$province': typeof ProvinceProvinceRouteWithChildren
  '/situations/$slug': typeof SituationsSlugRoute
  '/help': typeof HelpIndexRoute
  '/situations': typeof SituationsIndexRoute
  '/help/$category/$article': typeof HelpCategoryArticleRoute
  '/province/$province/$city': typeof ProvinceProvinceCityRoute
  '/help/$category': typeof HelpCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/founder': typeof FounderRoute
  '/get-vetted': typeof GetVettedRoute
  '/handbook': typeof HandbookRoute
  '/how-we-vet': typeof HowWeVetRoute
  '/province/$province': typeof ProvinceProvinceRouteWithChildren
  '/situations/$slug': typeof SituationsSlugRoute
  '/help/': typeof HelpIndexRoute
  '/situations/': typeof SituationsIndexRoute
  '/help/$category/$article': typeof HelpCategoryArticleRoute
  '/province/$province/$city': typeof ProvinceProvinceCityRoute
  '/help/$category/': typeof HelpCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/disclosure'
    | '/founder'
    | '/get-vetted'
    | '/handbook'
    | '/how-we-vet'
    | '/province/$province'
    | '/situations/$slug'
    | '/help/'
    | '/situations/'
    | '/help/$category/$article'
    | '/province/$province/$city'
    | '/help/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclosure'
    | '/founder'
    | '/get-vetted'
    | '/handbook'
    | '/how-we-vet'
    | '/province/$province'
    | '/situations/$slug'
    | '/help'
    | '/situations'
    | '/help/$category/$article'
    | '/province/$province/$city'
    | '/help/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/disclosure'
    | '/founder'
    | '/get-vetted'
    | '/handbook'
    | '/how-we-vet'
    | '/province/$province'
    | '/situations/$slug'
    | '/help/'
    | '/situations/'
    | '/help/$category/$article'
    | '/province/$province/$city'
    | '/help/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DisclosureRoute: typeof DisclosureRoute
  FounderRoute: typeof FounderRoute
  GetVettedRoute: typeof GetVettedRoute
  HandbookRoute: typeof HandbookRoute
  HowWeVetRoute: typeof HowWeVetRoute
  ProvinceProvinceRoute: typeof ProvinceProvinceRouteWithChildren
  SituationsSlugRoute: typeof SituationsSlugRoute
  HelpIndexRoute: typeof HelpIndexRoute
  SituationsIndexRoute: typeof SituationsIndexRoute
  HelpCategoryArticleRoute: typeof HelpCategoryArticleRoute
  HelpCategoryIndexRoute: typeof HelpCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-we-vet': {
      id: '/how-we-vet'
      path: '/how-we-vet'
      fullPath: '/how-we-vet'
      preLoaderRoute: typeof HowWeVetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook': {
      id: '/handbook'
      path: '/handbook'
      fullPath: '/handbook'
      preLoaderRoute: typeof HandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-vetted': {
      id: '/get-vetted'
      path: '/get-vetted'
      fullPath: '/get-vetted'
      preLoaderRoute: typeof GetVettedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations/': {
      id: '/situations/'
      path: '/situations'
      fullPath: '/situations/'
      preLoaderRoute: typeof SituationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations/$slug': {
      id: '/situations/$slug'
      path: '/situations/$slug'
      fullPath: '/situations/$slug'
      preLoaderRoute: typeof SituationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/province/$province': {
      id: '/province/$province'
      path: '/province/$province'
      fullPath: '/province/$province'
      preLoaderRoute: typeof ProvinceProvinceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$category/': {
      id: '/help/$category/'
      path: '/help/$category'
      fullPath: '/help/$category/'
      preLoaderRoute: typeof HelpCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/province/$province/$city': {
      id: '/province/$province/$city'
      path: '/$city'
      fullPath: '/province/$province/$city'
      preLoaderRoute: typeof ProvinceProvinceCityRouteImport
      parentRoute: typeof ProvinceProvinceRoute
    }
    '/help/$category/$article': {
      id: '/help/$category/$article'
      path: '/help/$category/$article'
      fullPath: '/help/$category/$article'
      preLoaderRoute: typeof HelpCategoryArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProvinceProvinceRouteChildren {
  ProvinceProvinceCityRoute: typeof ProvinceProvinceCityRoute
}

const ProvinceProvinceRouteChildren: ProvinceProvinceRouteChildren = {
  ProvinceProvinceCityRoute: ProvinceProvinceCityRoute,
}

const ProvinceProvinceRouteWithChildren =
  ProvinceProvinceRoute._addFileChildren(ProvinceProvinceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DisclosureRoute: DisclosureRoute,
  FounderRoute: FounderRoute,
  GetVettedRoute: GetVettedRoute,
  HandbookRoute: HandbookRoute,
  HowWeVetRoute: HowWeVetRoute,
  ProvinceProvinceRoute: ProvinceProvinceRouteWithChildren,
  SituationsSlugRoute: SituationsSlugRoute,
  HelpIndexRoute: HelpIndexRoute,
  SituationsIndexRoute: SituationsIndexRoute,
  HelpCategoryArticleRoute: HelpCategoryArticleRoute,
  HelpCategoryIndexRoute: HelpCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
