/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarterPackRouteImport } from './routes/starter-pack'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyPlanRouteImport } from './routes/my-plan'
import { Route as LocalHelpRouteImport } from './routes/local-help'
import { Route as HowWeVetRouteImport } from './routes/how-we-vet'
import { Route as HandbookRouteImport } from './routes/handbook'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as GetVettedRouteImport } from './routes/get-vetted'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FamilyCareKitRouteImport } from './routes/family-care-kit'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareCostsRouteImport } from './routes/care-costs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SituationsIndexRouteImport } from './routes/situations/index'
import { Route as HowToIndexRouteImport } from './routes/how-to/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as SituationsSlugRouteImport } from './routes/situations/$slug'
import { Route as ProvinceProvinceRouteImport } from './routes/province.$province'
import { Route as HowToSlugRouteImport } from './routes/how-to/$slug'
import { Route as DirectoryListingIdRouteImport } from './routes/directory_.$listingId'
import { Route as HelpCategoryIndexRouteImport } from './routes/help/$category/index'
import { Route as ProvinceProvinceCityRouteImport } from './routes/province.$province_.$city'
import { Route as HelpCategoryArticleRouteImport } from './routes/help/$category/$article'

const StarterPackRoute = StarterPackRouteImport.update({
  id: '/starter-pack',
  path: '/starter-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPlanRoute = MyPlanRouteImport.update({
  id: '/my-plan',
  path: '/my-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalHelpRoute = LocalHelpRouteImport.update({
  id: '/local-help',
  path: '/local-help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeVetRoute = HowWeVetRouteImport.update({
  id: '/how-we-vet',
  path: '/how-we-vet',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookRoute = HandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const GetVettedRoute = GetVettedRouteImport.update({
  id: '/get-vetted',
  path: '/get-vetted',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyCareKitRoute = FamilyCareKitRouteImport.update({
  id: '/family-care-kit',
  path: '/family-care-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareCostsRoute = CareCostsRouteImport.update({
  id: '/care-costs',
  path: '/care-costs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsIndexRoute = SituationsIndexRouteImport.update({
  id: '/situations/',
  path: '/situations/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToIndexRoute = HowToIndexRouteImport.update({
  id: '/how-to/',
  path: '/how-to/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsSlugRoute = SituationsSlugRouteImport.update({
  id: '/situations/$slug',
  path: '/situations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvinceProvinceRoute = ProvinceProvinceRouteImport.update({
  id: '/province/$province',
  path: '/province/$province',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToSlugRoute = HowToSlugRouteImport.update({
  id: '/how-to/$slug',
  path: '/how-to/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryListingIdRoute = DirectoryListingIdRouteImport.update({
  id: '/directory_/$listingId',
  path: '/directory/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCategoryIndexRoute = HelpCategoryIndexRouteImport.update({
  id: '/help/$category/',
  path: '/help/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvinceProvinceCityRoute = ProvinceProvinceCityRouteImport.update({
  id: '/province/$province_/$city',
  path: '/province/$province/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCategoryArticleRoute = HelpCategoryArticleRouteImport.update({
  id: '/help/$category/$article',
  path: '/help/$category/$article',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-costs': typeof CareCostsRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/disclosure': typeof DisclosureRoute
  '/family-care-kit': typeof FamilyCareKitRoute
  '/founder': typeof FounderRoute
  '/get-vetted': typeof GetVettedRoute
  '/guides': typeof GuidesRoute
  '/handbook': typeof HandbookRoute
  '/how-we-vet': typeof HowWeVetRoute
  '/local-help': typeof LocalHelpRoute
  '/my-plan': typeof MyPlanRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/starter-pack': typeof StarterPackRoute
  '/directory/$listingId': typeof DirectoryListingIdRoute
  '/how-to/$slug': typeof HowToSlugRoute
  '/province/$province': typeof ProvinceProvinceRoute
  '/situations/$slug': typeof SituationsSlugRoute
  '/help/': typeof HelpIndexRoute
  '/how-to/': typeof HowToIndexRoute
  '/situations/': typeof SituationsIndexRoute
  '/help/$category/$article': typeof HelpCategoryArticleRoute
  '/province/$province/$city': typeof ProvinceProvinceCityRoute
  '/help/$category/': typeof HelpCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-costs': typeof CareCostsRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/disclosure': typeof DisclosureRoute
  '/family-care-kit': typeof FamilyCareKitRoute
  '/founder': typeof FounderRoute
  '/get-vetted': typeof GetVettedRoute
  '/guides': typeof GuidesRoute
  '/handbook': typeof HandbookRoute
  '/how-we-vet': typeof HowWeVetRoute
  '/local-help': typeof LocalHelpRoute
  '/my-plan': typeof MyPlanRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/starter-pack': typeof StarterPackRoute
  '/directory/$listingId': typeof DirectoryListingIdRoute
  '/how-to/$slug': typeof HowToSlugRoute
  '/province/$province': typeof ProvinceProvinceRoute
  '/situations/$slug': typeof SituationsSlugRoute
  '/help': typeof HelpIndexRoute
  '/how-to': typeof HowToIndexRoute
  '/situations': typeof SituationsIndexRoute
  '/help/$category/$article': typeof HelpCategoryArticleRoute
  '/province/$province/$city': typeof ProvinceProvinceCityRoute
  '/help/$category': typeof HelpCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-costs': typeof CareCostsRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/disclosure': typeof DisclosureRoute
  '/family-care-kit': typeof FamilyCareKitRoute
  '/founder': typeof FounderRoute
  '/get-vetted': typeof GetVettedRoute
  '/guides': typeof GuidesRoute
  '/handbook': typeof HandbookRoute
  '/how-we-vet': typeof HowWeVetRoute
  '/local-help': typeof LocalHelpRoute
  '/my-plan': typeof MyPlanRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/starter-pack': typeof StarterPackRoute
  '/directory_/$listingId': typeof DirectoryListingIdRoute
  '/how-to/$slug': typeof HowToSlugRoute
  '/province/$province': typeof ProvinceProvinceRoute
  '/situations/$slug': typeof SituationsSlugRoute
  '/help/': typeof HelpIndexRoute
  '/how-to/': typeof HowToIndexRoute
  '/situations/': typeof SituationsIndexRoute
  '/help/$category/$article': typeof HelpCategoryArticleRoute
  '/province/$province_/$city': typeof ProvinceProvinceCityRoute
  '/help/$category/': typeof HelpCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/care-costs'
    | '/contact'
    | '/directory'
    | '/disclosure'
    | '/family-care-kit'
    | '/founder'
    | '/get-vetted'
    | '/guides'
    | '/handbook'
    | '/how-we-vet'
    | '/local-help'
    | '/my-plan'
    | '/privacy'
    | '/resources'
    | '/starter-pack'
    | '/directory/$listingId'
    | '/how-to/$slug'
    | '/province/$province'
    | '/situations/$slug'
    | '/help/'
    | '/how-to/'
    | '/situations/'
    | '/help/$category/$article'
    | '/province/$province/$city'
    | '/help/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/care-costs'
    | '/contact'
    | '/directory'
    | '/disclosure'
    | '/family-care-kit'
    | '/founder'
    | '/get-vetted'
    | '/guides'
    | '/handbook'
    | '/how-we-vet'
    | '/local-help'
    | '/my-plan'
    | '/privacy'
    | '/resources'
    | '/starter-pack'
    | '/directory/$listingId'
    | '/how-to/$slug'
    | '/province/$province'
    | '/situations/$slug'
    | '/help'
    | '/how-to'
    | '/situations'
    | '/help/$category/$article'
    | '/province/$province/$city'
    | '/help/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/care-costs'
    | '/contact'
    | '/directory'
    | '/disclosure'
    | '/family-care-kit'
    | '/founder'
    | '/get-vetted'
    | '/guides'
    | '/handbook'
    | '/how-we-vet'
    | '/local-help'
    | '/my-plan'
    | '/privacy'
    | '/resources'
    | '/starter-pack'
    | '/directory_/$listingId'
    | '/how-to/$slug'
    | '/province/$province'
    | '/situations/$slug'
    | '/help/'
    | '/how-to/'
    | '/situations/'
    | '/help/$category/$article'
    | '/province/$province_/$city'
    | '/help/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareCostsRoute: typeof CareCostsRoute
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  DisclosureRoute: typeof DisclosureRoute
  FamilyCareKitRoute: typeof FamilyCareKitRoute
  FounderRoute: typeof FounderRoute
  GetVettedRoute: typeof GetVettedRoute
  GuidesRoute: typeof GuidesRoute
  HandbookRoute: typeof HandbookRoute
  HowWeVetRoute: typeof HowWeVetRoute
  LocalHelpRoute: typeof LocalHelpRoute
  MyPlanRoute: typeof MyPlanRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  StarterPackRoute: typeof StarterPackRoute
  DirectoryListingIdRoute: typeof DirectoryListingIdRoute
  HowToSlugRoute: typeof HowToSlugRoute
  ProvinceProvinceRoute: typeof ProvinceProvinceRoute
  SituationsSlugRoute: typeof SituationsSlugRoute
  HelpIndexRoute: typeof HelpIndexRoute
  HowToIndexRoute: typeof HowToIndexRoute
  SituationsIndexRoute: typeof SituationsIndexRoute
  HelpCategoryArticleRoute: typeof HelpCategoryArticleRoute
  ProvinceProvinceCityRoute: typeof ProvinceProvinceCityRoute
  HelpCategoryIndexRoute: typeof HelpCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/starter-pack': {
      id: '/starter-pack'
      path: '/starter-pack'
      fullPath: '/starter-pack'
      preLoaderRoute: typeof StarterPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-plan': {
      id: '/my-plan'
      path: '/my-plan'
      fullPath: '/my-plan'
      preLoaderRoute: typeof MyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-help': {
      id: '/local-help'
      path: '/local-help'
      fullPath: '/local-help'
      preLoaderRoute: typeof LocalHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-vet': {
      id: '/how-we-vet'
      path: '/how-we-vet'
      fullPath: '/how-we-vet'
      preLoaderRoute: typeof HowWeVetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook': {
      id: '/handbook'
      path: '/handbook'
      fullPath: '/handbook'
      preLoaderRoute: typeof HandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-vetted': {
      id: '/get-vetted'
      path: '/get-vetted'
      fullPath: '/get-vetted'
      preLoaderRoute: typeof GetVettedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-care-kit': {
      id: '/family-care-kit'
      path: '/family-care-kit'
      fullPath: '/family-care-kit'
      preLoaderRoute: typeof FamilyCareKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-costs': {
      id: '/care-costs'
      path: '/care-costs'
      fullPath: '/care-costs'
      preLoaderRoute: typeof CareCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations/': {
      id: '/situations/'
      path: '/situations'
      fullPath: '/situations/'
      preLoaderRoute: typeof SituationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/': {
      id: '/how-to/'
      path: '/how-to'
      fullPath: '/how-to/'
      preLoaderRoute: typeof HowToIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations/$slug': {
      id: '/situations/$slug'
      path: '/situations/$slug'
      fullPath: '/situations/$slug'
      preLoaderRoute: typeof SituationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/province/$province': {
      id: '/province/$province'
      path: '/province/$province'
      fullPath: '/province/$province'
      preLoaderRoute: typeof ProvinceProvinceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/$slug': {
      id: '/how-to/$slug'
      path: '/how-to/$slug'
      fullPath: '/how-to/$slug'
      preLoaderRoute: typeof HowToSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory_/$listingId': {
      id: '/directory_/$listingId'
      path: '/directory/$listingId'
      fullPath: '/directory/$listingId'
      preLoaderRoute: typeof DirectoryListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$category/': {
      id: '/help/$category/'
      path: '/help/$category'
      fullPath: '/help/$category/'
      preLoaderRoute: typeof HelpCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/province/$province_/$city': {
      id: '/province/$province_/$city'
      path: '/province/$province/$city'
      fullPath: '/province/$province/$city'
      preLoaderRoute: typeof ProvinceProvinceCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$category/$article': {
      id: '/help/$category/$article'
      path: '/help/$category/$article'
      fullPath: '/help/$category/$article'
      preLoaderRoute: typeof HelpCategoryArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareCostsRoute: CareCostsRoute,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  DisclosureRoute: DisclosureRoute,
  FamilyCareKitRoute: FamilyCareKitRoute,
  FounderRoute: FounderRoute,
  GetVettedRoute: GetVettedRoute,
  GuidesRoute: GuidesRoute,
  HandbookRoute: HandbookRoute,
  HowWeVetRoute: HowWeVetRoute,
  LocalHelpRoute: LocalHelpRoute,
  MyPlanRoute: MyPlanRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  StarterPackRoute: StarterPackRoute,
  DirectoryListingIdRoute: DirectoryListingIdRoute,
  HowToSlugRoute: HowToSlugRoute,
  ProvinceProvinceRoute: ProvinceProvinceRoute,
  SituationsSlugRoute: SituationsSlugRoute,
  HelpIndexRoute: HelpIndexRoute,
  HowToIndexRoute: HowToIndexRoute,
  SituationsIndexRoute: SituationsIndexRoute,
  HelpCategoryArticleRoute: HelpCategoryArticleRoute,
  ProvinceProvinceCityRoute: ProvinceProvinceCityRoute,
  HelpCategoryIndexRoute: HelpCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
